
using System;
 
public class FigmaScreenNames {

    // Automatically generated by UnityFigmaBridge
          
	public const string MAIN_SCENCE="Main Scence";
	public const string TUTORIAL_SCENCE="Tutorial Scence";

}
